GET http://localhost:3232/pokemon/ditto

### Para crear un Pokemon
POST http://localhost:3232/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
    "transform"
  ]
}